const assert = require('node:assert/strict')
const base = process.env.SMOKE_BASE_URL || 'http://localhost:3001'
async function page(path) {
  const response = await fetch(`${base}${path}`)
  assert.equal(response.status, 200, `Unexpected status on ${path}`)
  return response.text()
}
async function main() {
  for (const locale of ['en', 'si', 'ta']) {
    const prefix = locale === 'en' ? '' : `/${locale}`
    const html = await page(`${prefix}/login`)
    assert.doesNotMatch(html, /aria-label="Customer navigation"/, 'Auth page must not show app navigation')
    assert.ok(html.includes(`href="${prefix}/terms"`), 'Terms link must retain locale')
    assert.doesNotMatch(html, /user-scalable=no|maximum-scale=1/)
    assert.match(html, /<label[^>]*for="[^"]+"/)
    console.log(`${prefix || '/en'}/login: clean auth layout, labels, locale links and zoom`)
    const forgot = await page(`${prefix}/forgot-password`)
    assert.doesNotMatch(forgot, /aria-label="Customer navigation"/)
    const home = await page(prefix || '/')
    assert.ok(home.includes(`href="${prefix}/about"`), 'About page must be discoverable and retain locale')
    assert.doesNotMatch(home, /Sarah Miller|James Wilson|Elena Rossi|5-Star Rated/)
    assert.match(home, /LKR 40,000/)
    assert.match(home, /aria-label="Luggo social media"/)
    assert.match(home, /href="https:\/\/www\.facebook\.com\/luggo\.lk"/)
    assert.match(home, /href="https:\/\/www\.instagram\.com\/luggo\.lk"/)
    const about = await page(`${prefix}/about`)
    assert.match(about, /About Luggo/)
    assert.match(about, /href="mailto:info@luggo\.lk"/)
    assert.ok(about.includes(`href="${prefix}/terms"`))
    const privacy = await page(`${prefix}/privacy`)
    assert.match(privacy, /href="mailto:info@luggo\.lk"/)
    assert.doesNotMatch(privacy, /gmail\.com/)
    const terms = await page(`${prefix}/terms`)
    assert.match(terms, /LKR 40,000/)
    assert.doesNotMatch(terms, /LKR 300,000|approximately \$1,000 USD/)
    console.log(`${prefix || '/en'}: About, domain contacts, social links, consistent guarantee and removed testimonials`)
  }
  const sitemap = await page('/sitemap.xml')
  assert.match(sitemap, /<loc>https:\/\/(?:www\.)?luggo\.lk\/about<\/loc>/)
  const maintenance = await page('/maintenance')
  assert.match(maintenance, /href="mailto:info@luggo\.lk"/)
  assert.doesNotMatch(maintenance, /gmail\.com/)
  const html = await page('/')
  assert.match(html, /aria-label="Language"/)
  const styles = [...html.matchAll(/href="([^"<>]+\.css[^"<>]*)"/g)].map(match => match[1].replace(/&amp;/g, '&'))
  assert.ok(styles.length)
  let css = ''
  for (const href of styles) css += await (await fetch(new URL(href, base))).text()
  assert.ok(css.includes('.text-brand-light'), 'Staff accent classes must be generated')
  assert.ok(css.includes('.app-dialog'), 'Dialog styles must be generated')
  assert.ok(css.includes('prefers-reduced-motion'), 'Reduced motion styles must be generated')
  console.log('UI route and generated-style checks passed.')
}
main().catch(error => { console.error(error); process.exitCode = 1 })
